services:
  - type: web
    name: landguardian
    runtime: python3
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT app:create_app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          type: postgresql
          name: landguardian-db
          property: connectionString
      - key: MAIL_DEFAULT_SENDER
        value: noreply@landguardian.onrender.com
